package com.pratham.dse.utils

/**
 * Created by Poonamchand Sahu 24 Jan 2020
 */
object AppConstant {
    val BASE_URL = "https://i-smartonline.com/EXAMAPK/"
    val IMAGE_BASE_URL = "https://i-smartonline.com/Exam_upload/"
    val API_KEY =
        "EQZBGPECQEIUUDQTBXCHBGEQZBGPECQEIUUDQTBXCHBGEQZBGPECQEIUUDQTEC5C1F4A-1736-4116-ACF1-25D47F41F54C"
    val OTP_ACTIVITY_FLAG = 10005
    val PHOTO_ACTIVITY_FLAG = 10006
    val AADHAAR_ACTIVITY_FLAG = 10007
    val SHIFT_DETAILS_ACTIVITY_FLAG = 10008
    val PROFILE_ACTIVITY_FLAG = 10009
    val PERMISSION_REQUEST_CODE_STORAGE = 50003
    val PERMISSION_REQUEST_CODE_CAMERA = 50004
    val PERMISSION_REQUEST_CODE_LOCATION = 50005
    val STATUS_SUCCESS = "Success"
    val STATUS_ERROR = "Error"
    val TYPE_ADMIN = "1"
    val TYPE_TECHNICIAN = "2"
    val TYPE_SC = "3"
    val DATE_FORMAT_YYYY_MM_DD = "yyyy/MM/dd"
    val DATE_FORMAT_DD_MMM_YYYY = "dd MMM, yyyy"
    val DATE_FORMAT_DD_MM_YYYY = "dd/MM/yyyy"
    val DATE_FORMAT_SERVER = "dd-MM-yyyy HH:mm:ss"
    val TIME_FORMAT = "HH:mm"
    val FLAG_ARRIVAL = "1"
    val FLAG_DEPARTURE = "2"
    val URL_ON_TIME_SHIFT_1="EXAM_APK_SAVE_EXAM_SHIFT_I_START_TIME"
    val URL_ON_TIME_SHIFT_2="EXAM_APK_SAVE_EXAM_SHIFT_II_START_TIME"
    val URL_ON_TIME_SHIFT_3="EXAM_APK_SAVE_EXAM_SHIFT_III_START_TIME"
    val URL_ON_TIME_SHIFT_4="EXAM_APK_SAVE_EXAM_SHIFT_IV_START_TIME"
    val SHIFT_1="Shift 1"
    val SHIFT_2="Shift 2"
    val SHIFT_3="Shift 3"
    val SHIFT_4="Shift 4"
    val URL_OFF_TIME_SHIFT_1="EXAM_APK_SAVE_EXAM_SHIFT_I_END_TIME"
    val URL_OFF_TIME_SHIFT_2="EXAM_APK_SAVE_EXAM_SHIFT_II_END_TIME"
    val URL_OFF_TIME_SHIFT_3="EXAM_APK_SAVE_EXAM_SHIFT_III_END_TIME"
    val URL_OFF_TIME_SHIFT_4="EXAM_APK_SAVE_EXAM_SHIFT_IV_END_TIME"
    val PRESENT="1"
    val ABSENT="1"
    val URL_MID_ATTANDANCE_SHIFT_1="EXAM_APK_SAVE_EXAM_SHIFT_I_MID_ATTENDANCE_TIME"
    val URL_MID_ATTANDANCE_SHIFT_2="EXAM_APK_SAVE_EXAM_SHIFT_II_MID_ATTENDANCE_TIME"
    val URL_MID_ATTANDANCE_SHIFT_3="EXAM_APK_SAVE_EXAM_SHIFT_III_MID_ATTENDANCE_TIME"
    val URL_MID_ATTANDANCE_SHIFT_4="EXAM_APK_SAVE_EXAM_SHIFT_IV_MID_ATTENDANCE_TIME"
    val URL_UPLOAD_FILE_SHIFT_1="EXAM_APK_SAVE_EXAM_SHIFT_I_Upload"
    val URL_UPLOAD_FILE_SHIFT_2="EXAM_APK_SAVE_EXAM_SHIFT_II_Upload"
    val URL_UPLOAD_FILE_SHIFT_3="EXAM_APK_SAVE_EXAM_SHIFT_III_Upload"
    val URL_UPLOAD_FILE_SHIFT_4="EXAM_APK_SAVE_EXAM_SHIFT_IV_Upload"
    val URL_SAVE_EXAM_SHIFT_I_ISSUE="EXAM_APK_SAVE_EXAM_SHIFT_I_ISSUE"
    val URL_SAVE_EXAM_SHIFT_II_ISSUE="EXAM_APK_SAVE_EXAM_SHIFT_II_ISSUE"
    val URL_SAVE_EXAM_SHIFT_III_ISSUE="EXAM_APK_SAVE_EXAM_SHIFT_III_ISSUE"
    val URL_SAVE_EXAM_SHIFT_IV_ISSUE="EXAM_APK_SAVE_EXAM_SHIFT_IV_ISSUE"



}